---
- name: HomeLab VMs Creation
  hosts: homelab
  tasks:
    - name: create Windows 10 virtual machine
      vars_prompt:
        - name   : "api_host"
          prompt : "PVE API host?: "
          default: "localhost"
          private: no
        - name   : "api_node"
          prompt : "PVE API node?: "
    #      default: "{{ ansible_nodename }}"
          private: no
        - name   : "api_user"
          prompt : "PVE API user?: "
          default: "root@pam"
          private: no
        - name   : "api_password"
          prompt : "PVE API password?: "
          private: yes
      proxmox_kvm:
        api_user    : "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host    : "{{ api_host }}"
        node        : "{{ api_node }}"
        vmid: 110
        name: lab-win10
        balloon: 0
        bios: ovmf
        bootdisk: virtio0
        cores: 4
        sockets: 2
        vcpus: 4
        cpu: host
        kvm: 0
        memory: 8192
        machine: q35
        hostpci:
          hostpci0: 'host="01:00",pcie="0",rombar="1",x-vga="1"'
        hotplug: disk,network,usb,memory,cpu
        scsi:
          scsi0: 'local-lvm:64,format="raw",cache="writeback"'
        ide:
          ide2: 'local:iso/windows10.iso,media="cdrom"'
        ostype: win10
        net:
          net0: 'e1000="1A:28:29:AE:00:01",bridge="vmbr1"'
