---
- name: HomeLab VMs Creation
  hosts: homelab
  tasks:
    - name: create pfSense virtual machine
      vars_prompt:
        - name   : "api_host"
          prompt : "PVE API host?: "
          default: "localhost"
          private: no
        - name   : "api_node"
          prompt : "PVE API node?: "
    #      default: "{{ ansible_nodename }}"
          private: no
        - name   : "api_user"
          prompt : "PVE API user?: "
          default: "root@pam"
          private: no
        - name   : "api_password"
          prompt : "PVE API password?: "
          private: yes
      proxmox_kvm:
        api_user    : "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host    : "{{ api_host }}"
        node        : "{{ api_node }}"
        vmid: 100
        name: lab-fir01
        balloon: 1024
        bootdisk: virtio0
        cores: 1
        sockets: 1
        vcpus: 1
        memory: 2048
        virtio:
          virtio0: 'local-pve:16,format="raw",cache="writeback"'
        ide:
          ide2: 'local.iso="pfSence.iso",media="cdrom"'
        ostype: l26
        net:
          net0: 'virtio,bridge="vmbr0"'
          net1: 'virtio,bridge="vmbr1"'
          net2: 'virtio,bridge="vmbr2"'
          net3: 'virtio,bridge="vmbr3"'
