---
- name: PVE Configuration
  hosts: pve
  vars:
    proxmox_interfaces_template: 'interfaces.new.j2'
    proxmox_interfaces_wan: 'enp0s31f6'
    proxmox_restrict_webadmin: true
    proxmox_pveproxy_allow_from: '127.0.0.1,192.168.1.0/24'
    proxmox_pcipassthrough_enabled: true
    proxmox_storages:
    - id: backup
      type: dir
      path: /var/lib/vz/dump
      maxFiles: 1
      content: backup # images,iso,vztmpl,backup
      nodes: myProxmoxHostname # hostname
  roles:
    - proxmox

# Create VM
- name: HomeLab VM Creation
  hosts: homelab
  vars_prompt:
    - name   : "api_host"
      prompt : "PVE API host?: "
      default: "localhost"
      private: no
    - name   : "api_user"
      prompt : "PVE API user?: "
      default: "root@pam"
      private: no
    - name   : "api_password"
      prompt : "PVE API password?: "
      private: yes
  tasks:
    - name: create Windows 10 virtual machine
      proxmox_kvm:
        api_user    : "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host    : "{{ api_host }}"
        node        : "kuja"
        vmid: 110
        name: lab-win10
        balloon: 0
        bios: seabios
        bootdisk: virtio0
        cores: 3
        sockets: 2
        vcpus: 4
        cpu: host
        kvm: 0
        memory: 16384
        machine: q35
        hostpci:
          hostpci0: 'host="01:00",pcie="0",rombar="1",x-vga="1"'
        hotplug: disk,network,usb,memory,cpu
        virtio:
          virtio0: 'local-pve:64,format="raw",cache="writeback"'
        ide:
          ide2: 'local,iso="windows10.iso",media="cdrom"'
        ostype: win8
        net:
          net0: 'e1000="1A:28:29:AE:00:01",bridge="vmbr1"'
