---
- name: ensure pve-enterprise repo is disable (need a valid subscription)
  file:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    state: "absent"

- name: ensure valid subscription banner is disabled
  lineinfile:
    path: "/usr/share/pve-manager/js/pvemanagerlib.js"
    regexp: '(^.*)data.status !== \'Active\'(.*$)'
    line: '\1false\2'
