---
# tasks file for pve-iscsi

- name: Setup open-iscsi configuration
  template:
    src: "{{ proxmox_isci_config_template }}"
    dest: "{{ proxmox_isci_config_file }}"
  notify: open-iscsi restart
