---
# tasks file for proxmox-pxeproxy

- name: Create default configuration for pveproxy
  template:
    src: "etc-default/pveproxy"
    dest: "/etc/default/pveproxy"
  notify: pveproxy restart
  when: proxmox_pveproxy_restrict_webadmin
