# Edit to fit your need then rename the file to fit your host ansible_name

proxmox_fqdn: pomerium.shk

proxmox_wan_interface: 'enp7s0'
proxmox_lan_interface: 'enp0s31f6'
proxmox_vmbr2_enabled: true
proxmox_vmbr2_desc: 'DMZ'
proxmox_vmbr3_enabled: true

proxmox_pveproxy_restrict_webadmin: true
proxmox_pveproxy_allow_from: "127.0.0.1,192.168.0.0/16"

proxmox_pcipassthrough_enabled: true

proxmox_storages:
  - id: backup
    type: dir
    path: /var/lib/vz/dump
    maxFiles: 1
    content: backup # images,iso,vztmpl,backup
    node: "{{ ansible_nodename }}"
